// Code generated by Kitex v0.3.4. DO NOT EDIT.

package usersrv

import (
	"context"
	"example.com/cloud/protogen/kitex_gen/services/account"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UserGetBe(ctx context.Context, Req *account.UserGetBeReq, callOptions ...callopt.Option) (r *account.UserGetBeResp, err error)
	UserListBe(ctx context.Context, Req *account.UserListBeReq, callOptions ...callopt.Option) (r *account.UserListBeResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserSrvClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserSrvClient struct {
	*kClient
}

func (p *kUserSrvClient) UserGetBe(ctx context.Context, Req *account.UserGetBeReq, callOptions ...callopt.Option) (r *account.UserGetBeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserGetBe(ctx, Req)
}

func (p *kUserSrvClient) UserListBe(ctx context.Context, Req *account.UserListBeReq, callOptions ...callopt.Option) (r *account.UserListBeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserListBe(ctx, Req)
}
