// Code generated by Kitex v0.3.4. DO NOT EDIT.

package usercentersrv

import (
	"context"
	"example.com/cloud/protogen/kitex_gen/apps/usercenter"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UserGet(ctx context.Context, Req *usercenter.UserGetReq, callOptions ...callopt.Option) (r *usercenter.UserGetResp, err error)
	UserList(ctx context.Context, Req *usercenter.UserListReq, callOptions ...callopt.Option) (r *usercenter.UserListResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserCenterSrvClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserCenterSrvClient struct {
	*kClient
}

func (p *kUserCenterSrvClient) UserGet(ctx context.Context, Req *usercenter.UserGetReq, callOptions ...callopt.Option) (r *usercenter.UserGetResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserGet(ctx, Req)
}

func (p *kUserCenterSrvClient) UserList(ctx context.Context, Req *usercenter.UserListReq, callOptions ...callopt.Option) (r *usercenter.UserListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserList(ctx, Req)
}
