// Code generated by Kitex v0.3.4. DO NOT EDIT.
package usercentersrv

import (
	"example.com/cloud/protogen/kitex_gen/apps/usercenter"
	"github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler usercenter.UserCenterSrv, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
